cod_P1, num_P1, valor_P1 = input(). split()
cod_P1 = int(cod_P1)
num_P1 = int(num_P1)
valor_P1 = float(valor_P1)
cod_P2, num_P2, valor_P2 = input(). split()
cod_P2 = int(cod_P2)
num_P2 = int(num_P2)
valor_P2 = float(valor_P2)
Total = (num_P1*valor_P1) + (num_P2*valor_P2)
print("VALOR A PAGAR: R$ %.2f" %Total)