A, B, C = input() .split()
A = float(A)
B = float(B)
C = float(C)
triangulo = float(A * C /2)
circulo = float(3.14159 * C**2)
trapezio = float(((A + B) * C) /2)
quadrado = float(B * B)
retangulo = float(A * B)
print("TRIANGULO: %0.3f" %triangulo)
print("CIRCULO: %0.3f" %circulo)
print("TRAPEZIO: %0.3f" %trapezio)
print("QUADRADO: %0.3f" %quadrado)
print("RETANGULO: %0.3f" %retangulo)